[package]
name = "aoc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ranges = "0.3.3"
rayon = "1.6.1"

[profile.release]
lto = true
